### ISSUE TITLE
Date Published is empty on Default report

### ISSUE THREAD

**Issue by mikejmets** [senaite/senaite.impress#68]
## Steps to reproduce
Publish a Sample
Select the Default report

## Current behavior
Date Published is empty

## Expected behavior
Date Published has either the date of publication or the current date time

**Comment by grulisco** [comment]
@mikejmets: 
If I got the idea of https://github.com/senaite/senaite.impress/pull/69 correctly, you have to keep in mind:

The initial report will show the current date, but if you create subsequent reports into the sample, it will always show the publication date of the preceding one instead of the current one in progress, which is not correct.

IMHO the report in progress should show the current date, even when there will be a small lag of a few minutes to the logged date of the final transition of publication.

**Comment by mikejmets** [comment]
Good point @grulisco. I'll change it rather always use the current date time.

**Comment by mikejmets** [comment]
I've changed the publication date to always use current datetime at per suggestion from @grulisco
